### ISSUE TITLE
Fix Registration.  crashing...body not defined

### ISSUE THREAD

**Issue by dctabion** [dctabion/the-welcome-net#14]
View not getting volunteer object.

**Comment by dctabion** [comment]
POST /api/volunteers 500 20.697 ms - 3099
---callback: Receive response from API call to POST new volunteer
body:  <!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"><title></title><link rel="stylesheet" href="/bootstrap-3.3.6-dist/css/bootstrap.min.css"><link rel="stylesheet" href="/stylesheets/style.css"></head><body><div class="navbar navbar-default navbar-fixed-top"><div class="container"><div class="navbar-header"><a href="/" class="navbar-brand">The Welcome Net</a><button type="button" data-toggle="collapse" data-target="#navbar-main" class="navbar-toggle"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button></div><div id="navbar-main" class="navbar-collapse collapse"><ul class="nav navbar-nav"><li><a href="/volunteers/new">Register</a></li><li><a href="/volunteers">Volunteer List</a></li></ul></div></div></div><div class="container"><h1>body is not defined</h1><h2></h2><pre>ReferenceError: body is not defined
    at module.exports.volunteersCreate (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/app_api/controllers/volunteers.js:180:50)
    at Layer.handle [as handle_request](/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/layer.js:95:5)
    at /Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request](/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/index.js:312:13)
    at /Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/index.js:271:10)
    at /Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/express/lib/router/index.js:618:15</pre><footer><div class="row"><div class="col-xs-12"><small>&copy; Double Haul Productions 2016</small></div></div></footer></div><script src="/javascripts/jquery.min.js"></script><script src="/bootstrap-3.3.6-dist/js/bootstrap.min.js"></script></body></html>
/Users/macdannyt/DansStuff/DCTech/the_welcome_net/app_server/controllers/volunteers.js:153
        first_name: body.volunteer.first_name,
                                  ^

TypeError: Cannot read property 'first_name' of undefined
    at Request._callback (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/app_server/controllers/volunteers.js:153:35)
    at Request.self.callback (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/request/request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/macdannyt/DansStuff/DCTech/the_welcome_net/node_modules/request/request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by dctabion** [comment]
config was undefined when calling packageAndSendResponseForAdd()
